[package]
name = "flux-codegen-swift"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flux-syntax.workspace = true
flux-ir.workspace = true
flux-parser.workspace = true
flux-types.workspace = true
flux-codegen-core.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
criterion.workspace = true

[[bench]]
name = "codegen"
harness = false
