[package]
name = "flux-differ"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flux-syntax.workspace = true
flux-ir.workspace = true
ahash.workspace = true
smallvec.workspace = true

[dev-dependencies]
criterion.workspace = true
proptest.workspace = true

[[bench]]
name = "diff"
harness = false
