[package]
name = "flux-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "flux"
path = "src/main.rs"

[dependencies]
flux-devserver.workspace = true
flux-codegen-swift.workspace = true
flux-codegen-kotlin.workspace = true
clap.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
