// AUTO-GENERATED by scripts/generate_for_each_hashes.sh — DO NOT EDIT.
// Computes blake3 closure hashes from bytecode blobs that match
// flux_ir_serde::hash_closure (Appendix D §D.7).
// Re-run after changing ForEachBytecode.textThunkBytecode or addTaskBytecode.

import Foundation

@MainActor
enum ForEachHashConstants {
    /// blake3 of textThunkBytecode with signals=[100] (itemSlot).
    static let thunkHash: [UInt8] = [133, 117, 188, 185, 241, 155, 112, 195]
    /// blake3 of addTaskBytecode with no captured signals.
    static let addHandlerHash: [UInt8] = [136, 54, 122, 79, 233, 245, 216, 148]
}
