/**
 * check-i18n-drift.ts
 *
 * Fails the build if any English doc slug under `src/content/docs/en` lacks a
 * Spanish counterpart under `src/content/docs/es`. Content-only pages (the
 * autogenerated ADR mirror is an exception noted below) must ship in both
 * locales so the site never serves an untranslated page behind the language
 * switcher.
 *
 * The ADR directory (`en/adr`) is an exception: ADRs are ingested verbatim
 * from the repo and are English-only source-of-truth documents. Spanish
 * readers get the English ADR with the built-in untranslated-content notice.
 *
 * Run with: `pnpm check:i18n` (also invoked during `pnpm build` after ingest).
 */
import { readdir } from 'node:fs/promises';
import { join, dirname, relative, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const docsDir = join(__dirname, '..', 'src', 'content', 'docs');

/** Directories excluded from the EN/ES parity requirement. */
const EXEMPT_DIRS = new Set(['adr']);

/** Returns the slug-relative set of doc paths (without extension) for a locale. */
async function slugSet(locale: string): Promise<Set<string>> {
  const localeDir = join(docsDir, locale);
  const slugs = new Set<string>();
  const walk = async (dir: string) => {
    let entries: import('node:fs').Dirent[];
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(full);
      } else if (/\.(md|mdx)$/.test(entry.name)) {
        const rel = relative(localeDir, full).replace(/\\/g, '/');
        slugs.add(rel.slice(0, -extname(rel).length));
      }
    }
  };
  await walk(localeDir);
  return slugs;
}

/**
 * Verifies that every translatable EN doc has an ES counterpart. Returns the
 * list of missing ES slugs (empty when clean).
 */
export async function findMissingTranslations(): Promise<string[]> {
  const en = await slugSet('en');
  const es = await slugSet('es');
  const missing: string[] = [];
  for (const slug of en) {
    const topSegment = slug.split('/')[0] ?? '';
    if (EXEMPT_DIRS.has(topSegment)) continue;
    if (!es.has(slug)) missing.push(slug);
  }
  return missing;
}

const isMain =
  process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  try {
    const missing = await findMissingTranslations();
    if (missing.length > 0) {
      console.error('i18n drift detected — missing ES translations:');
      for (const slug of missing) console.error(`  - es/${slug}`);
      console.error(
        '\nTranslate the missing pages or add them under src/content/docs/es.',
      );
      process.exit(1);
    }
    console.log('check-i18n-drift: EN/ES parity OK (ADR mirror exempt).');
  } catch (err) {
    console.error(err instanceof Error ? err.message : err);
    process.exit(1);
  }
}
