//! T-503 / ADR-0059: generate committed wire fixtures from the Rust encoder.
//!
//! Writes four files to `fixtures/wire/`:
//!   - `init_v2.bin`   — minimal Init frame, protocol v2 (legacy layout)
//!   - `delta_v2.bin`  — Delta frame with one Update patch, protocol v2
//!   - `init_v3.bin`   — same tree, protocol v3 (u32 length prefixes, ADR-0059)
//!   - `delta_v3.bin`  — same patch, protocol v3
//!
//! The v2/v3 pairs share structural content, so a byte diff pinpoints exactly
//! which prefixes ADR-0059 widened. v2 fixtures stay committed so cross-host
//! decoders can regression-test the legacy layout; the Rust decoder in
//! `flux-ir-serde` accepts both, and (per ADR-0059) Swift and Kotlin gain the
//! same dual-version support in lockstep.
//!
//! `unsupported-version.bin` is generated by the `round_trip` test.
//!
//! Run:  cargo run -p flux-ir-serde --example dump_fixtures

use flux_ir_serde::Frame;
use flux_syntax::{Child, NodeKind, Patch, PropDiff, Props, Span, StringId, StringTable, Value};

fn main() {
    let fixture_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../fixtures/wire");
    std::fs::create_dir_all(&fixture_dir).unwrap();

    // ---- Structural content (identical for v2 and v3) ----
    let mut table = StringTable::new();
    let label = table.intern("Increment");

    let root = flux_syntax::NodeRef {
        id: 1,
        kind: NodeKind::Component,
        component_id: 1,
        props: Props::from_fields(vec![(0u16, Value::Str(label))]),
        children: vec![Child::Node(3), Child::Node(2)],
        handlers: vec![],
        span: Span::new(0, 0, 10),
    };

    let patches = vec![Patch::Update {
        id: 3,
        props_diff: PropDiff {
            changes: vec![(0u16, Value::Str(StringId::from(99u32)))],
            removals: vec![],
        },
    }];
    let strings: Vec<(StringId, String)> = table
        .iter()
        .map(|(id, text)| (id, text.to_owned()))
        .collect();

    // ---- Version-parameterized builders ----
    let build_init = |version: u8| -> Vec<u8> {
        let mut frame = Frame::init(
            &root,
            &[],
            &[],
            &[
                (0u32, "src/main.flux".to_string()),
                (1u32, "stdlib/button.flux".to_string()),
            ],
            &table,
            &[(1u32, "Button".to_string()), (2u32, "Text".to_string())],
            &[],
            &[],
        );
        frame.version = version;
        frame.to_bytes()
    };
    let build_delta = |version: u8| -> Vec<u8> {
        let mut frame = Frame::delta(0, 0, &patches, &strings, &[], &[]);
        frame.version = version;
        frame.to_bytes()
    };

    // ---- v2 (legacy; decoder regression coverage) ----
    let init_v2 = build_init(2);
    std::fs::write(fixture_dir.join("init_v2.bin"), &init_v2).expect("write init_v2.bin");
    println!("wrote init_v2.bin ({} bytes)", init_v2.len());

    let delta_v2 = build_delta(2);
    std::fs::write(fixture_dir.join("delta_v2.bin"), &delta_v2).expect("write delta_v2.bin");
    println!("wrote delta_v2.bin ({} bytes)", delta_v2.len());

    // ---- v3 (current protocol) ----
    let init_v3 = build_init(3);
    std::fs::write(fixture_dir.join("init_v3.bin"), &init_v3).expect("write init_v3.bin");
    println!("wrote init_v3.bin ({} bytes)", init_v3.len());

    let delta_v3 = build_delta(3);
    std::fs::write(fixture_dir.join("delta_v3.bin"), &delta_v3).expect("write delta_v3.bin");
    println!("wrote delta_v3.bin ({} bytes)", delta_v3.len());
}
