//! T-503: generate committed wire fixtures from the Rust encoder (source of truth).
//!
//! Writes two files to `fixtures/wire/`:
//!   - `init_v2.bin`  — a minimal Init frame (one Text + one Button)
//!   - `delta_v2.bin` — a Delta frame with one prop-change Update patch
//!
//! `unsupported-version.bin` is already generated by the existing
//! `unsupported_protocol_version_fixture_matches_and_is_rejected` test.
//!
//! Run:  cargo run -p flux-ir-serde --example dump_fixtures

use flux_ir_serde::{serialize_patches, Frame};
use flux_syntax::{
    Child, NodeKind, Patch, PropDiff, Props, Span,
    StringId, StringTable, Value,
};

fn main() {
    let fixture_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../fixtures/wire");
    std::fs::create_dir_all(&fixture_dir).unwrap();

    // ---- init_v2.bin: minimal tree (Text + Button) ----
    let mut table = StringTable::new();
    let label = table.intern("Increment");
    let button_text = table.intern("Save");

    // Button node (id=2): Primitive with a text prop (no handlers to keep
    // the fixture self-contained — the existing unsupported-version test
    // uses the same shape).
    let button = flux_syntax::NodeRef {
        id: 2,
        kind: NodeKind::Primitive,
        component_id: 0,
        props: Props::from_fields(vec![(0u16, Value::Str(button_text))]),
        children: vec![],
        handlers: vec![],
        span: Span::new(1, 0, 8),
    };

    // Text node (id=3): leaf child of root.
    let _text_node = flux_syntax::NodeRef {
        id: 3,
        kind: NodeKind::Primitive,
        component_id: 0,
        props: Props::from_fields(vec![(0u16, Value::Str(label))]),
        children: vec![],
        handlers: vec![],
        span: Span::new(1, 0, 6),
    };

    // Root: Component with two children (Text, Button).
    let root = flux_syntax::NodeRef {
        id: 1,
        kind: NodeKind::Component,
        component_id: 1,
        props: Props::from_fields(vec![(0u16, Value::Str(label))]),
        children: vec![Child::Node(3), Child::Node(2)],
        handlers: vec![],
        span: Span::new(0, 0, 10),
    };

    let init_frame = Frame::init(
        &root,
        &[],
        &[],
        &[
            (0u32, "src/main.flux".to_string()),
            (1u32, "stdlib/button.flux".to_string()),
        ],
        &table,
        &[(1u32, "Button".to_string()), (2u32, "Text".to_string())],
        &[],
        &[],
    );

    let init_bytes = init_frame.to_bytes();
    std::fs::write(fixture_dir.join("init_v2.bin"), &init_bytes)
        .expect("write init_v2.bin");
    println!("wrote init_v2.bin ({} bytes)", init_bytes.len());

    // ---- delta_v2.bin: one prop-change Update patch ----
    let patches = vec![Patch::Update {
        id: 3,
        props_diff: PropDiff {
            changes: vec![(0u16, Value::Str(StringId::from(99u32)))],
            removals: vec![],
        },
    }];
    let delta_bytes = serialize_patches(&patches, &table, &[]);
    std::fs::write(fixture_dir.join("delta_v2.bin"), &delta_bytes)
        .expect("write delta_v2.bin");
    println!("wrote delta_v2.bin ({} bytes)", delta_bytes.len());
}
