#!/bin/bash
# Generates ForEachHashConstants.swift with blake3 closure hashes
# computed from the bytecode blobs in ForEachBytecode.
# Run: bash scripts/generate_for_each_hashes.sh
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
COMPUTE_HASH="${HOME}/.hermes/scripts/compute_hash_flux"

if [ ! -x "${COMPUTE_HASH}" ]; then
    echo "Error: compute_hash_flux binary not found at ${COMPUTE_HASH}"
    echo "Build it with: cd /tmp/compute_hash_flux && cargo build --release"
    exit 1
fi

# Thunk bytecode: READ_SIGNAL r0, 100; GET_FIELD r2, labelIdx(6141), r0;
# ALLOC_RECORD r1, 1; SET_FIELD r1, labelIdx(6141), r2; HALT
THUNK_HEX="1000640000007102fd1700700101007201fd170200"
THUNK_HASH=$("${COMPUTE_HASH}" "${THUNK_HEX}" "100")

# AddTask handler bytecode: reads newTask(200), builds Task record, pushes to
# tasks(201), resets newTask(200) to str(10).
ADD_HEX="1000c8000000700102007201fd1700b202007201f17f021003c900000081030111c900000003b3040a00000011c80000000400"
ADD_HASH=$("${COMPUTE_HASH}" "${ADD_HEX}" "")

cat > "${SCRIPT_DIR}/../runtimes/ios/FluxHost/Tests/FluxHostTests/ForEachHashConstants.swift" << SWIFT
// AUTO-GENERATED by scripts/generate_for_each_hashes.sh — DO NOT EDIT.
// Computes blake3 closure hashes from bytecode blobs that match
// flux_ir_serde::hash_closure (Appendix D §D.7).
// Re-run after changing ForEachBytecode.textThunkBytecode or addTaskBytecode.

import Foundation

@MainActor
enum ForEachHashConstants {
    /// blake3 of textThunkBytecode with signals=[100] (itemSlot).
    static let thunkHash: [UInt8] = ${THUNK_HASH}
    /// blake3 of addTaskBytecode with no captured signals.
    static let addHandlerHash: [UInt8] = ${ADD_HASH}
}
SWIFT

echo "Generated ForEachHashConstants.swift"
echo "  thunkHash:       ${THUNK_HASH}"
echo "  addHandlerHash:  ${ADD_HASH}"
