[package]
name = "flux-codegen-kotlin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
flux-syntax.workspace = true
flux-ir.workspace = true
thiserror.workspace = true

[dev-dependencies]
insta.workspace = true
